const characters = [
  "Abraham Simpson",
  "Agnes Skinner",
  "Akira Kurosawa",
  "Alice Glick",
  "Apu Nahasapeemapetilon",
  "Arnie Pye",
  "Artie Ziff",
  "Baby Gerald",
  "Barney Gumble",
  "Bart Simpson",
  "Bernice Hibbert",
  "Bleeding Gums Murphy",
  "Booberella",
  "Brandine Spuckler",
  "Bumblebee Man",
  "Carl Carlson",
  "Chief Clancy Wiggum",
  "Cletus Spuckler",
  "Comic Book Guy",
  "Cookie Kwan",
  "Crazy Cat Lady",
  "Dewey Largo",
  "Disco Stu",
  "Dolph Starbeam",
  "Dr. Julius Hibbert",
  "Dr. Marvin Monroe",
  "Dr. Nick Riviera",
  "Drederick Tatum",
  "Duffman",
  "Eddie",
  "Edna Krabappel",
  "Elizabeth Hoover",
  "Fat Tony",
  "Gil Gunderson",
  "Groundskeeper Willie",
  "Hans Moleman",
  "Helen Lovejoy",
  "Herman Hermann",
  "Homer Simpson",
  "Hyman Krustofski",
  "Itchy & Scratchy",
  "Jacqueline Bouvier",
  "Jasper Beardsley",
  "Jimbo Jones",
  "Johnny Tightlips",
  "Judge Roy Snyder",
  "Julio Franco",
  "Kang & Kodos",
  "Kearney Zzyzwicz",
  "Kent Brockman",
  "Kirk Van Houten",
  "Krusty the Clown",
  "Kumiko Albertson",
  "Legs",
  "Lenny Leonard",
  "Lindsey Naegle",
  "Lionel Hutz",
  "Lisa Simpson",
  "Lou",
  "Louie",
  "Luann Van Houten",
  "Luigi Risotto",
  "Lunchlady Doris",
  "Maggie Simpson",
  "Manjula Nahasapeemapetilon",
  "Marge Simpson",
  "Martin Prince",
  "Maude Flanders",
  "Mayor Joe Quimby",
  "Milhouse Van Houten",
  "Miss Springfield",
  "Moe Szyslak",
  "Mona Simpson",
  "Mr. Burns",
  "Mr. Teeny",
  "Mrs. Muntz",
  "Mrs. Vanderbilt",
  "Ned Flanders",
  "Nelson Muntz",
  "Old Jewish Man",
  "Otto Mann",
  "Patty Bouvier",
  "Principal Seymour Skinner",
  "Professor Jonathan Frink",
  "Rainier Wolfcastle",
  "Ralph Wiggum",
  "Reverend Timothy Lovejoy",
  "Rod Flanders",
  "Roger Meyers, Jr.",
  "Ruth Powers",
  "Santa’s Little Helper",
  "Sarah Wiggum",
  "Sea Captain",
  "Selma Bouvier",
  "Shauna Chalmers",
  "Sherri & Terri",
  "Sideshow Bob",
  "Sideshow Mel",
  "Snake Jailbird",
  "Snowball II",
  "Snowball V",
  "Squeaky-Voiced Teen",
  "Superintendent Gary Chalmers",
  "The Rich Texan",
  "The Yes Guy",
  "Todd Flanders",
  "Troy McClure",
  "Waylon Smithers",
  "Wise Guy",
  "Üter Zörker",
];
export default characters;
