const characters = [
  "Abraham Grampa Simpson",
  "Agnes Skinner",
  "Alice Glick",
  "Apu Nahasapeemapetilon",
  "Arnie Pye",
  "Artie Ziff",
  "Barney Gumble",
  "Bart Simpson",
  "Bleeding Gums Murphy",
  "Brandine Spuckler",
  "Bumblebee Man",
  "Carl Carlson",
  "Chief Clancy Wiggum",
  "Cletus Spuckler",
  "Comic Book Guy",
  "Cookie Kwan",
  "Crazy Cat Lady",
  "Disco Stu",
  "Dr Julius Hibbert",
  "Dr Marvin Monroe",
  "Dr Nick Riviera",
  "Drederick Tatum",
  "Duffman",
  "Edna Krabappel",
  "Elizabeth Hoover",
  "Fat Tony",
  "Gil Gunderson",
  "Groundskeeper Willie",
  "Hans Moleman",
  "Helen Lovejoy",
  "Herman Hermann",
  "Homer Simpson",
  "Jacqueline Bouvier",
  "Jasper Beardsley",
  "Jimbo Jones",
  "Judge Roy Snyder",
  "Kearney Zzyzwicz",
  "Kent Brockman",
  "Kirk Van Houten",
  "Krusty the Clown",
  "Lenny Leonard",
  "Lionel Hutz",
  "Lisa Simpson",
  "Luann Van Houten",
  "Luigi Risotto",
  "Lunchlady Doris",
  "Maggie Simpson",
  "Manjula Nahasapeemapetilon",
  "Marge Simpson",
  "Martin Prince",
  "Maude Flanders",
  "Mayor Joe Quimby",
  "Milhouse Van Houten",
  "Moe Szyslak",
  "Mona Simpson",
  "Montgomery Burns",
  "Mrs Muntz",
  "Ned Flanders",
  "Nelson Muntz",
  "Officer Eddie",
  "Officer Lou",
  "Otto Mann",
  "Patty Bouvier",
  "Principal Seymour Skinner",
  "Professor Frink",
  "Rainier Wolfcastle",
  "Ralph Wiggum",
  "Reverend Timothy Lovejoy",
  "Rod Flanders",
  "Sea Captain",
  "Selma Bouvier",
  "Sherri and Terri",
  "Sideshow Bob",
  "Sideshow Mel",
  "Snake Jailbird",
  "Squeaky-Voiced Teen",
  "Superintendent Gary Chalmers",
  "The Rich Texan",
  "Todd Flanders",
  "Troy McClure",
  "Waylon Smithers",
  "Uter Zorker",
];
export default characters;
